# Our main route
/:
  # Load up the default layout file, this
  # should ALWAYS be the first thing listed
  layout

  # Before filter, this executes these files
  # in order before page is rendered
  before:
    pdo
    install/verify_install  # Check to make sure the schema has been installed
    links                   # Get list of links

  # Fill in regions defined in the layout
  regions:
    body: home

# Site installation
/install:
  install

  before:
    pdo
    install/schema    # Defines our schema
    install/install   # Procedes with installation

# User login
/login:
  layout

  before:
    pdo
    users/login       # Check if user is trying to login

  regions: 
    body: login       # Present user with login form

# User logout
/logout:

  before:
    users/logout

# Delete links
/delete:

  before:
    users/verify_login
    pdo
    users/verify_can_delete
    delete

# Create links
/create:
  layout

  before:
    users/verify_login
    users/verify_can_create
    pdo
    create
